--- 
extensions: 
- json
- another-extension
name: jqmobilestore
bbver: 4.6
sdk: /Library/Ruby/Gems/1.8/gems/rhodes-3.1.1
applog: rholog.txt
build: debug
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
vendor: rhomobile
sdkversion: 2.3.0
iphone: 
  BundleURLScheme: jqmobilestore
  provisionprofile: 
  BundleIdentifier: com.rhomobile.jqmobilestore
  sdk: iphonesimulator4.0
  entitlements: 
  codesignidentity: 
  configuration: Debug
